routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'confirm' => false, // Password Confirm Routes...
  'verify' => false, // Email Verification Routes...
]);


Route::group(['middleware' => 'auth'],function(){
    Route::get('/', function () {
        return view('welcome');
    });


    Route::group(['middleware' => 'Roles:Super Admin'], function () {
      // route hari efektif
      Route::group(['prefix' => 'hari-efektif', 'as' => 'hari-efektif.'],function() {
        Route::get('/', 'HariEfektifController@index')
          ->name('index');
        Route::put('/update/{data}', 'HariEfektifController@update')
          ->name('update');
      });
  
      // route jurusan
      Route::resource('jurusan', 'JurusanController')->except([
        'show'
      ]);
  
      // route user
      Route::resource('/user', 'UserController');
  
      // route user role
      Route::get('/user/{user}/addrole', 'UserController@addRole')
        ->name('user.add-role');
      Route::post('/user/{user}/storerole', 'UserController@storeRole')
        ->name('user.store-role');
      Route::delete('/user/{user}/removerole/{userRole}', 'UserController@removeRole')
        ->name('user.remove-role');
      Route::post('/user/{user}/reset-password', 'UserController@resetPassword')
        ->name('user.reset-password');
  
      //route kategori point
      Route::resource('kategori-point', 'KategoriPointController');
  
      // route point
      Route::get('/kategori-point/{kategori_point}/point', 'PointController@create')
        ->name('kategori-point.show.create');
      Route::post('/kategori-point/{kategori_point}/point', 'PointController@store')
        ->name('kategori-point.show.store');
      Route::get('/kategori-point/{kategori_point}/point/{point}/edit', 'PointController@edit')
        ->name('kategori-point.show.edit');
      Route::patch('/kategori-point/{kategori_point}/point/{point}/update', 'PointController@update')
        ->name('kategori-point.show.update');
      Route::delete('/kategori-point/{kategori_point}/point/{point}', 'PointController@destroy')
        ->name('kategori-point.show.destroy');

      //route hari tidak efektif
      Route::resource('hari-tidak-efektif', 'HariTidakEfektifController')->except([
        'show'
      ]);
        
    });




    // route kelas
    Route::resource('kelas', 'KelasController')->parameters([
      'kelas' => 'kelas'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route siswa
    Route::resource('/kelas/{kelas}/siswa', 'SiswaController')->except([
      'index'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route kasus
    Route::resource('/kasus', 'KasusController')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_siswa/{siswa}', 'KasusController@getSiswa')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_point/{point}', 'KasusController@getPoint')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::put('kasus/{kasus}/rollback', 'KasusController@rollback')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.rollback');

    //  route absensi
    Route::get('/absensi', 'AbsensiController@index')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.index');
    Route::get('/absensi/{kelas}', 'AbsensiController@showKelas')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.show-kelas');
    Route::get('/absensi/{kelas}/create', 'AbsensiController@create')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.create');
    Route::POST('/absensi/{kelas}/store', 'AbsensiController@store')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.store');
    Route::get('/absensi/{kelas}/edit', 'AbsensiController@edit')
      ->middleware('Roles:Super Admin')
      ->name('absensi.edit');
    Route::POST('/absensi/{kelas}/edit/get-data', 'AbsensiController@getDataSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.edit.get-data');
    Route::PUT('/absensi/{kelas}/update', 'AbsensiController@update')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.update');
});




/*
|--------------------------------------------------------------------------
| Web Routes Data Tables
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware'=> 'auth', 'prefix' => 'datatables', 'as' => 'datatables.'],function(){
    Route::get('hari-efektif/json', 'HariEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-efektif');

    Route::get('jurusan/json', 'JurusanController@json')
      ->middleware('Roles:Super Admin')
      ->name('jurusan');

    Route::get('kelas/json', 'KelasController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas');

    Route::get('kelas/{kelas}/siswa/json', 'SiswaController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa');

    Route::get('/kelas/{kelas}/siswa/{siswa}/pelanggaran/json', 'SiswaController@getPelanggaran')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.pelanggaran');

    Route::get('/kelas/{kelas}/siswa/{siswa}/penghargaan/json', 'SiswaController@getPenghargaan')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.penghargaan');

    Route::get('/users/json', 'UserController@json')
      ->middleware('Roles:Super Admin')
      ->name('user');

    Route::get('/hari-tidak-efektif/json', 'HariTidakEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-tidak-efektif');

    Route::get('/kategori-point/json', 'KategoriPointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point');

    Route::get('kategori-point/{kategori_point}/point/json', 'PointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point.show.point');

    Route::get('/kasus/json', 'KasusController@json')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus');

    Route::get('absensi/json', 'AbsensiController@json')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi');

    Route::get('absensi/{kelas}/json', 'AbsensiController@jsonSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.siswa');

});




/*
|--------------------------------------------------------------------------
| Web Routes Select 2
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware' => 'auth', 'prefix' => 'select2', 'as' => 'select2.'],function(){
    Route::post('/kasus/kelas/{kelas}/siswa', 'KasusController@siswa')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.siswa');

    Route::post('/kasus/{kategori_point}/point', 'KasusController@point')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.point');

    Route::post('kelas/guru/json', 'KelasController@guru')
      ->middleware('Roles:Super Admin')
      ->name('kelas.guru');

});

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    protected $table = "siswa";
    protected $fillable = [
        "nis",
        "kelas_id",
        "nama",
        "agama",
        "alamat",
        "domisili",
        "tempat_lahir",
        "tanggal_lahir",
        "no_telp",
        "foto",
        "point_pelanggaran",
        "point_penghargaan",
    ];

    function pelanggaran() {
        return $this->hasMany(Pelanggaran::class);
    }
    function absensi() {
        return $this->hasMany(Absensi::class);
    }
    function kelas() {
        return $this->belongsTo(Kelas::class);
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Siswa;
use App\Models\Kelas;
use App\Models\Kasus;
use App\Http\Requests\SiswaRequest;
use Illuminate\Http\Request;
use DB;
use Roles;

class SiswaController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Kelas $kelas)
    {
        return view('siswa.create', compact('kelas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SiswaRequest $request, Kelas $kelas)
    {
        $schema = $request->all() + [
            'kelas_id' => $kelas->id,
            'point_pelanggaran' => 0,
            'point_penghargaan' => 0
        ];
        
        $siswa = new Siswa($schema);

        try{

            if($siswa->save()){
                return redirect()
                    ->route('siswa.show',[ $siswa, $kelas])
                    ->with('success','Siswa berhasil ditambahkan');
            }else{
                return redirect()
                    ->route('kelas.show', $kelas)
                    ->with('error','Siswa gagal ditambahkan.');
            }
        }catch(\Exception $e){
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('error','Siswa gagal ditambahkan.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas, Siswa $siswa)
    {
        if($siswa->kelas_id === $kelas->id){
            if(Roles::has('Super Admin')){
                return view('siswa.show', compact('kelas', 'siswa'));
            }else{
                $isMatch = $kelas->user_id === Roles::getId();
                if($isMatch){
                    return view('siswa.show', compact('kelas', 'siswa'));
                }
                return abort(403);
            }
        }else{
            return abort(404);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas, Siswa $siswa)
    {
        return view('siswa.edit', compact('kelas', 'siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function update(SiswaRequest $request, Kelas $kelas, Siswa $siswa)
    {
        if($siswa->update( $request->all() )){
            return redirect()
                ->route('siswa.show', [$kelas, $siswa] )
                ->with('success', 'Siswa berhasil diubah.');
        }else{
            return redirect()
                ->route('siswa.show', [$kelas, $siswa] )
                ->with('error', 'Siswa gagal diubah.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Siswa  $siswa
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kelas $kelas,Siswa $siswa)
    {
        DB::beginTransaction();
        try{
            $siswa->delete();
            DB::commit();
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('success', 'Siswa berhasil dihapus.');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('error', 'Siswa gagal dihapus. Masih ada data absensi dan/atau kasus yang ter-relasi dengan data ini.');
        }
    }

    public function json(Kelas $kelas){
        if(Roles::has('Super Admin')){
            $siswa = Siswa::where( ['kelas_id' => $kelas->id] )
                    ->select( ['nip','nama','point_pelanggaran','point_penghargaan','kelas_id'] )
                    ->get();
        }else{
            $siswa = Siswa::where( ['kelas_id' => $kelas->id, 'kelas.user_id' => Roles::getId() ] )
                    ->join('kelas', 'kelas.id', 'kelas_id')
                    ->select( ['nip','nama','point_pelanggaran','point_penghargaan','kelas_id'] )
                    ->get();
        }

        $datatable = datatables()
            ->of($siswa)
            ->addColumn('action',function($data){
                $routeUpdate = route('siswa.edit', [$data->kelas_id, $data] );
                $routeDetail = route('siswa.show', [$data->kelas_id, $data] );
                $routeDestroy = route('siswa.destroy', [$data->kelas_id, $data] );

                $token = csrf_token();
                $csrf = "<input type='hidden' value='$token' name='_token'>";
                $method = "<input type='hidden' value='DELETE' name='_method'>";
                
                $buttonUpdate = "
                            <a href='$routeUpdate' class='btn btn-primary mb-1 mr-1'>
                                <i class='fa fa-pencil-alt'></i> Ubah
                            </a>";
                $buttonDetail = "
                            <a href='$routeDetail' class='btn btn-warning mb-1 mr-1'>
                                <i class='fa fa-eye'></i> Detail
                            </a>";
                $buttonDestroy = "
                            <form action='$routeDestroy' method='post' class='d-inline-block'> 
                                $csrf 
                                $method 
                                <button class='btn btn-danger mb-1 mr-1 deleteAlerts'>
                                    <i class='fa fa-trash'></i> Hapus
                                </button>
                            </form>";
                

                if(\Roles::has('Super Admin')){
                    $button = "$buttonUpdate $buttonDetail $buttonDestroy";
                }else{
                    $button = "$buttonDetail";
                }
                return $button;
            })
            ->make(true);

        return $datatable;

    }

    public function getPelanggaran(Kelas $kelas,Siswa $siswa){
        $kasus = Kasus::join('point', 'point.id', 'point_id')
            ->join('kategori_point', 'kategori_point.id', 'point.kategori_point_id')
            ->join('siswa', 'siswa.nip', 'siswa_nip')
            ->where( ['kategori_point.jenis_point' => 'negatif'] )
            ->select( ['tanggal', 'point.peraturan', 'point.point'] )
            ->get();

        $datatables = datatables()
            ->of($kasus)
            ->addColumn('petugas', function($data){
                return $data->name;
            })
            ->editColumn('tanggal', function($data){
                return \CStr::date($data->tanggal);
            })
            ->make(true);

        return $datatables;
    }
    public function getPenghargaan(Kelas $kelas,Siswa $siswa){
        $kasus = Kasus::join('point', 'point.id', 'point_id')
            ->join('kategori_point', 'kategori_point.id', 'point.kategori_point_id')
            ->join('siswa', 'siswa.nip', 'siswa_nip')
            ->where( ['kategori_point.jenis_point' => 'positif'] )
            ->select( ['tanggal', 'point.peraturan', 'point.point'] )
            ->get();

        $datatables = datatables()
            ->of($kasus)
            ->addColumn('petugas', function($data){
                return $data->name;
            })
            ->editColumn('tanggal', function($data){
                return \CStr::date($data->tanggal);
            })
            ->make(true);

        return $datatables;
    }
}

resources/views/temp/siswa/create.blade.php
@extends('layouts.main')

@push('title', 'Tambah Siswa')
@push('header-title', 'Tambah Siswa')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-body">
            <form action="{{ route('siswa.store', $kelas) }}" method="POST" class="form">
                @csrf
                <div class="form-group">
                    <label for="nip">NIP <span class="text-danger">*</span></label>
                    <input type="text" name="nip" id="nip" class="form-control">
                </div>
                <div class="form-group">
                    <label for="nama">Nama Lengkap <span class="text-danger">*</span></label>
                    <input type="text" name="nama" id="nama" class="form-control">
                </div>
                <div class="form-group">
                    <label for="alamat_rumah">Alamat Rumah <span class="text-danger">*</span></label>
                    <textarea type="text" name="alamat_rumah" id="alamat_rumah" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="alamat_domisili">Alamat Domisili <span class="text-danger">*</span></label>
                    <textarea type="text" name="alamat_domisili" id="alamat_domisili" class="form-control"></textarea>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="tempat_lahir">Tempat Lahir <span class="text-danger">*</span></label>
                            <input type="text" name="tempat_lahir" id="tempat_lahir" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="tanggal_lahir">Tanggal Lahir <span class="text-danger">*</span></label>
                            <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="no_telp">No Telp <span class="text-danger">*</span></label>
                    <input type="text" name="no_telp" id="no_telp" class="form-control" placeholder="+62">
                </div>
                <div class="form-group">
                    <label for="nama_wali">Nama Wali <span class="text-danger">*</span></label>
                    <input type="text" name="nama_wali" id="nama_wali" class="form-control">
                </div>
                <div class="form-group">
                    <label for="no_telp_wali">No Telp Wali <span class="text-danger">*</span></label>
                    <input type="text" name="no_telp_wali" id="no_telp_wali" class="form-control" placeholder="+62">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-submit">
                        Submit
                    </button>
                    <a href="{{ route('kelas.show', $kelas) }}" class="btn btn-danger">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(document).ready(function () {
        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            Swal.fire({
                title: "Apakah anda yakin?",
                text: "Data akan ditambahkan ke dalam database setelah proses ini dijalankan.",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya!",
                cancelButtonText: 'Tidak',
            }).then((result) => {
                if (result.value) form.submit();
            });
        });
    });

</script>
@endpush

resources/views/temp/siswa/edit.blade.php
@extends('layouts.main')

@push('title', 'Ubah Siswa')
@push('header-title', 'Ubah Siswa')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-body">
            <form action="{{ route('siswa.update', [$kelas, $siswa]) }}" method="POST" class="form">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="nip">NIP <span class="text-danger">*</span></label>
                    <input type="text" name="nip" id="nip" class="form-control" value="{{ $siswa->nip }}" disabled>
                </div>
                <div class="form-group">
                    <label for="nama">Nama Lengkap <span class="text-danger">*</span></label>
                    <input type="text" name="nama" id="nama" class="form-control" value="{{ $siswa->nama }}">
                </div>
                <div class="form-group">
                    <label for="alamat_rumah">Alamat Rumah <span class="text-danger">*</span></label>
                    <textarea type="text" name="alamat_rumah" id="alamat_rumah"
                        class="form-control">{{ $siswa->alamat_rumah }}</textarea>
                </div>
                <div class="form-group">
                    <label for="alamat_domisili">Alamat Domisili <span class="text-danger">*</span></label>
                    <textarea type="text" name="alamat_domisili" id="alamat_domisili"
                        class="form-control">{{ $siswa->alamat_domisili }}</textarea>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="tempat_lahir">Tempat Lahir <span class="text-danger">*</span></label>
                            <input type="text" name="tempat_lahir" id="tempat_lahir" class="form-control"
                                value="{{ $siswa->tempat_lahir }}">
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="tanggal_lahir">Tanggal Lahir <span class="text-danger">*</span></label>
                            <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control"
                                value="{{ $siswa->tanggal_lahir }}">
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="no_telp">No Telp <span class="text-danger">*</span></label>
                    <input type="text" name="no_telp" id="no_telp" class="form-control" placeholder="+62"
                        value="{{ $siswa->no_telp }}">
                </div>
                <div class="form-group">
                    <label for="nama_wali">Nama Wali <span class="text-danger">*</span></label>
                    <input type="text" name="nama_wali" id="nama_wali" class="form-control"
                        value="{{ $siswa->nama_wali }}">
                </div>
                <div class="form-group">
                    <label for="no_telp_wali">No Telp Wali <span class="text-danger">*</span></label>
                    <input type="text" name="no_telp_wali" id="no_telp_wali" class="form-control" placeholder="+62"
                        value="{{ $siswa->no_telp_wali }}">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-submit">
                        Submit
                    </button>
                    <a href="{{ route('kelas.show', $kelas) }}" class="btn btn-danger">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(document).ready(function () {
        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            Swal.fire({
                title: "Apakah anda yakin?",
                text: "Data akan ditambahkan ke dalam database setelah proses ini dijalankan.",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya!",
                cancelButtonText: 'Tidak',
            }).then((result) => {
                if (result.value) form.submit();
            });
        });
    });

</script>
@endpush

resources/views/temp/siswa/show.blade.php
@extends('layouts.main')

@push('title', 'Detail Siswa')
@push('header-title', 'Detail Siswa')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-danger">
        <div class="card-header">
            <a href="{{ route('kelas.show', $kelas) }}" class="btn btn-danger">Kembali</a>
        </div>
        <div class="card-body">
            <table class="table table-borderless table-hover">
                <tr>
                    <th>NIP</th>
                    <td>{{ $siswa->nip }}</td>
                </tr>
                <tr>
                    <th>Nama</th>
                    <td>{{ $siswa->nama }}</td>
                </tr>
                <tr>
                    <th>TTL</th>
                    <td>{{ $siswa->tempat_lahir }}, {{ $siswa->tanggal_lahir }}</td>
                </tr>
                <tr>
                    <th>Alamat</th>
                    <td>{{ $siswa->alamat_rumah }}</td>
                </tr>
                <tr>
                    <th>Domisili</th>
                    <td>{{ $siswa->alamat_domisili }}</td>
                </tr>
                <tr>
                    <th>No Telp</th>
                    <td>{{ $siswa->no_telp }}</td>
                </tr>
                <tr>
                    <th>Nama Wali</th>
                    <td>{{ $siswa->nama_wali }}</td>
                </tr>
                <tr>
                    <th>No Telp Wali</th>
                    <td>{{ $siswa->no_telp_wali }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card card-primary">
        <div class="card-header">
            <h3>Riwayat Penghargaan : <strong>{{ $siswa->point_penghargaan }}</strong> Point</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover table-borderless w-100" id="table-penghargaan">
                <thead>
                    <th>Tanggal</th>
                    <th>Kasus</th>
                    <th>Point</th>
                </thead>
            </table>
        </div>
    </div>
</div>
<div class="col-md-6">
    <div class="card card-primary">
        <div class="card-header">
            <h3>Riwayat Pelanggaran : <strong>{{ $siswa->point_pelanggaran }}</strong> Point</h3>
        </div>
        <div class="card-body">
            <table class="table table-hover table-borderless w-100" id="table-pelanggaran">
                <thead>
                    <th>Tanggal</th>
                    <th>Kasus</th>
                    <th>Point</th>
                </thead>
            </table>

        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(function () {
        $('#table-penghargaan').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: "{{ route('datatables.kelas.show.siswa.penghargaan', [$kelas, $siswa] ) }}",
            columns: [{
                    data: 'tanggal',
                    name: 'tanggal'
                },
                {
                    data: 'peraturan',
                    name: 'peraturan'
                },
                {
                    data: 'point',
                    name: 'point'
                },
            ],
        });
        $('#table-pelanggaran').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: "{{ route('datatables.kelas.show.siswa.pelanggaran', [$kelas, $siswa] ) }}",
            columns: [{
                    data: 'tanggal',
                    name: 'tanggal'
                },
                {
                    data: 'peraturan',
                    name: 'peraturan'
                },
                {
                    data: 'point',
                    name: 'point'
                },
            ],
        });
    });

</script>
@endpush