routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'confirm' => false, // Password Confirm Routes...
  'verify' => false, // Email Verification Routes...
]);


Route::group(['middleware' => 'auth'],function(){
    Route::get('/', function () {
        return view('welcome');
    });


    Route::group(['middleware' => 'Roles:Super Admin'], function () {
      // route hari efektif
      Route::group(['prefix' => 'hari-efektif', 'as' => 'hari-efektif.'],function() {
        Route::get('/', 'HariEfektifController@index')
          ->name('index');
        Route::put('/update/{data}', 'HariEfektifController@update')
          ->name('update');
      });
  
      // route jurusan
      Route::resource('jurusan', 'JurusanController')->except([
        'show'
      ]);
  
      // route user
      Route::resource('/user', 'UserController');
  
      // route user role
      Route::get('/user/{user}/addrole', 'UserController@addRole')
        ->name('user.add-role');
      Route::post('/user/{user}/storerole', 'UserController@storeRole')
        ->name('user.store-role');
      Route::delete('/user/{user}/removerole/{userRole}', 'UserController@removeRole')
        ->name('user.remove-role');
      Route::post('/user/{user}/reset-password', 'UserController@resetPassword')
        ->name('user.reset-password');
  
      //route kategori point
      Route::resource('kategori-point', 'KategoriPointController');
  
      // route point
      Route::get('/kategori-point/{kategori_point}/point', 'PointController@create')
        ->name('kategori-point.show.create');
      Route::post('/kategori-point/{kategori_point}/point', 'PointController@store')
        ->name('kategori-point.show.store');
      Route::get('/kategori-point/{kategori_point}/point/{point}/edit', 'PointController@edit')
        ->name('kategori-point.show.edit');
      Route::patch('/kategori-point/{kategori_point}/point/{point}/update', 'PointController@update')
        ->name('kategori-point.show.update');
      Route::delete('/kategori-point/{kategori_point}/point/{point}', 'PointController@destroy')
        ->name('kategori-point.show.destroy');

      //route hari tidak efektif
      Route::resource('hari-tidak-efektif', 'HariTidakEfektifController')->except([
        'show'
      ]);
        
    });




    // route kelas
    Route::resource('kelas', 'KelasController')->parameters([
      'kelas' => 'kelas'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route siswa
    Route::resource('/kelas/{kelas}/siswa', 'SiswaController')->except([
      'index'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route kasus
    Route::resource('/kasus', 'KasusController')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_siswa/{siswa}', 'KasusController@getSiswa')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_point/{point}', 'KasusController@getPoint')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::put('kasus/{kasus}/rollback', 'KasusController@rollback')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.rollback');

    //  route absensi
    Route::get('/absensi', 'AbsensiController@index')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.index');
    Route::get('/absensi/{kelas}', 'AbsensiController@showKelas')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.show-kelas');
    Route::get('/absensi/{kelas}/create', 'AbsensiController@create')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.create');
    Route::POST('/absensi/{kelas}/store', 'AbsensiController@store')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.store');
    Route::get('/absensi/{kelas}/edit', 'AbsensiController@edit')
      ->middleware('Roles:Super Admin')
      ->name('absensi.edit');
    Route::POST('/absensi/{kelas}/edit/get-data', 'AbsensiController@getDataSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.edit.get-data');
    Route::PUT('/absensi/{kelas}/update', 'AbsensiController@update')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.update');
});




/*
|--------------------------------------------------------------------------
| Web Routes Data Tables
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware'=> 'auth', 'prefix' => 'datatables', 'as' => 'datatables.'],function(){
    Route::get('hari-efektif/json', 'HariEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-efektif');

    Route::get('jurusan/json', 'JurusanController@json')
      ->middleware('Roles:Super Admin')
      ->name('jurusan');

    Route::get('kelas/json', 'KelasController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas');

    Route::get('kelas/{kelas}/siswa/json', 'SiswaController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa');

    Route::get('/kelas/{kelas}/siswa/{siswa}/pelanggaran/json', 'SiswaController@getPelanggaran')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.pelanggaran');

    Route::get('/kelas/{kelas}/siswa/{siswa}/penghargaan/json', 'SiswaController@getPenghargaan')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.penghargaan');

    Route::get('/users/json', 'UserController@json')
      ->middleware('Roles:Super Admin')
      ->name('user');

    Route::get('/hari-tidak-efektif/json', 'HariTidakEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-tidak-efektif');

    Route::get('/kategori-point/json', 'KategoriPointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point');

    Route::get('kategori-point/{kategori_point}/point/json', 'PointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point.show.point');

    Route::get('/kasus/json', 'KasusController@json')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus');

    Route::get('absensi/json', 'AbsensiController@json')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi');

    Route::get('absensi/{kelas}/json', 'AbsensiController@jsonSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.siswa');

});




/*
|--------------------------------------------------------------------------
| Web Routes Select 2
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware' => 'auth', 'prefix' => 'select2', 'as' => 'select2.'],function(){
    Route::post('/kasus/kelas/{kelas}/siswa', 'KasusController@siswa')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.siswa');

    Route::post('/kasus/{kategori_point}/point', 'KasusController@point')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.point');

    Route::post('kelas/guru/json', 'KelasController@guru')
      ->middleware('Roles:Super Admin')
      ->name('kelas.guru');

});

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Absensi;
use App\Models\Kelas;
use App\Models\Siswa;
use App\Models\HariEfektif;
use App\Models\HariTidakEfektif;
use App\Http\Requests\AbsensiRequest;
use Illuminate\Http\Request;
use DB;

class AbsensiController extends Controller
{
    public function getDayNow(){
        $today = date('D');
        $days = [
            'Sun' => "Minggu",
            'Mon' => "Senin",
            'Tue' => "Selasa",
            'Wed' => "Rabu",
            'Thu' => "Kamis",
            'Fri' => "Jum'at",
            'Sat' => "Sabtu",
        ];
     
        return $days[$today];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
        return view('absensi.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Kelas $kelas)
    {
        $prefixKelas = $kelas->getPrefix();
        $today = date('Y-m-d');
        $daynow = $this->getDayNow();
        $hariTidakEfektf = HariTidakEfektif::where( ['tanggal' => $today] )
            ->first();
        $hariEfektif = HariEfektif::where( ['hari' => $daynow] )
            ->first();
        $absenHariIni = Absensi::join('siswa', 'siswa.nip', 'siswa_nip')
            ->join('kelas', 'kelas.id', 'kelas_id')
            ->where( ['tanggal' => $today, 'kelas.id' => $kelas->id] )
            ->get();
        
        // dependensi
        $status = ["alpha", "ijin", "sakit", "bolos"];
        $siswaDB = Siswa::where( ['kelas_id' => $kelas->id] )
            ->orderBy('nama','ASC')
            ->get();

        $siswa = [];
        foreach($siswaDB as $row){
            $siswa += [$row->nip => $row->nama];
        }

        if($hariTidakEfektf){
            return redirect()
                ->route('absensi.show-kelas', $kelas)
                ->with('error', "Hari ini libur dikarenakan $hariTidakEfektf->keterangan");
        }else{
            if($hariEfektif->status){
                if( count($absenHariIni) > 0){
                    return redirect()
                        ->route('absensi.show-kelas', $kelas)
                        ->with('error', "Kelas $prefixKelas Hari ini telah diabsen.");
                }else{
                    return view('absensi.create', compact('kelas', 'status', 'siswa'));
                }
                
            }else{
                return redirect()
                    ->route('absensi.show-kelas', $kelas)
                    ->with('error', "$hariEfektif->hari bukan hari efektif");
            }
        }

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AbsensiRequest $request,Kelas $kelas)
    {
        $today = date('Y-m-d');
        $user = auth()->user()->id;
        $countData = count($request->siswa_nip);
        $nips = [];

        foreach($request->siswa_nip as $row){
            array_push($nips,$row);
        }
        
        $siswaHadir = Siswa::whereNotIn('nip',$nips)
            ->get();

        DB::beginTransaction();

        try{
            // Insert Siswa Hadir
            foreach($siswaHadir as $row){
                $schema = [
                    'tanggal' => $today,
                    'status' => 'hadir',
                    'keterangan' => '-',
                    'siswa_nip' => $row->nip,
                    'user_id' => $user
                ];
                $absensi = new Absensi($schema);
                $absensi->save();
            }
            // Insert Siswa Tidak Hadir
            for($i=0;$i<$countData;$i++){
                $schema = [
                    'tanggal' => $today,
                    'status' => $request->status[$i],
                    'keterangan' => $request->keterangan[$i],
                    'siswa_nip' => $request->siswa_nip[$i],
                    'user_id' => $user
                ];
                $absensi = new Absensi($schema);
                $absensi->save();
            }
            DB::commit();
            return redirect()
                ->route('absensi.show-kelas', $kelas)
                ->with('success', 'Absensi berhasil ditambahkan.');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()
                ->route('absensi.show-kelas', $kelas)
                ->with('success', 'Gagal menambahkan absensi.');
        }


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Absensi  $absensi
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas)
    {
        $status = ['alpha', 'ijin', 'sakit', 'bolos', 'hadir'];
        $siswaDB = Siswa::where( ['kelas_id' => $kelas->id] )
            ->orderBy('nama','ASC')
            ->get();

        $siswa = [];
        foreach($siswaDB as $row){
            $siswa += [$row->nip => $row->nama];
        }

        return view('absensi.edit' , compact('kelas', 'status', 'siswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Absensi  $absensi
     * @return \Illuminate\Http\Response
     */
    public function update(AbsensiRequest $request,Kelas $kelas)
    {
        $absensi = Absensi::where([
            'id' => $request->id, 
            'siswa_nip' => $request->siswa_nip
        ])->first();

        $schema = [
            "status" => $request->status,
            "keterangan" => $request->keterangan
        ];

        try{
            $absensi->update($schema);

            return redirect()
                ->route('absensi.show-kelas', $kelas)
                ->with('success', 'Absensi berhasil diubah');
        }catch(\Exception $e){
            return redirect()
                ->route('absensi.show-kelas', $kelas)
                ->with('error', 'Absensi gagal diubah');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Absensi  $absensi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Absensi $absensi)
    {
        //
    }



    public function jsonSiswa(Request $request,Kelas $kelas){
        $tanggal = date('Y-m-d');

        if( $request->tanggal != "" ){
            $tanggal = $request->tanggal;
        }

        $data = Absensi::where([ 'tanggal' => $tanggal, 'kelas_id' => $kelas->id ])
            ->where('status','!=','hadir')
            ->join('siswa','siswa.nip','siswa_nip')
            ->join('kelas','kelas.id','kelas_id')
            ->select( ['siswa.nip', 'siswa.nama', 'tanggal', 'absensi.status', 'absensi.keterangan'] )
            ->get();

        return datatables()
            ->of($data)
            ->editColumn('tanggal',function($data) {
                return \CStr::date($data->tanggal);
            })
            ->editColumn('status',function($data) {
                return strtoupper($data->status);
            })
            ->make(true);
    }


    public function json(Request $request,Kelas $kelas){

        $data = Kelas::get();

        $today = date('Y-m-d');

        $kelasTelahAbsenHariIni = Absensi::join('siswa', 'siswa.nip', 'siswa_nip')
            ->join('kelas', 'kelas.id', 'kelas_id')
            ->join('jurusan', 'jurusan.id', 'jurusan_id')
            ->select('tanggal','kelas_id')
            ->groupBy('tanggal','kelas_id')
            ->having('tanggal',$today)
            ->get();

        $datatables = datatables()
                ->of($data,$kelasTelahAbsenHariIni)
                ->addColumn('prefix',function($data) {
                    return $data->getPrefix();
                })
                ->addColumn('status_absen_hari_ini',function($data) use($kelasTelahAbsenHariIni) {
                    $retString = "Belum Diabsen";
                    foreach($kelasTelahAbsenHariIni as $row){
                        if($data->id == $row->kelas_id){
                            $retString = "Sudah Diabsen";
                        }
                    }
                    return $retString;
                })
                ->removeColumn([
                    'grade',
                    'kelas_x',
                    'kelas_xi',
                    'kelas_xii',
                    'jurusan_id',
                    'user_id',
                    'created_at',
                    'updated_at',
                ])
                ->addColumn('action',function($data){
                    $routeDetail = route('absensi.show-kelas', $data);
                    
                    $buttonDetail = "
                            <a href='$routeDetail' class='btn btn-warning mb-1 mr-1'>
                                <span class='fas fa-eye'></span> Detail
                            </a>";

                    $button = "$buttonDetail";
                    return $button;
                })
                ->make(true);
        
        return $datatables;
    }


    public function showKelas(Kelas $kelas){
        return view('absensi.show-kelas', compact('kelas'));
    }

    public function getDataSiswa(Request $request,Kelas $kelas){
        
        $tanggal = $request->tanggal;
        $nip = $request->nip;

        $absensi = Absensi::join('siswa', 'siswa.nip', 'siswa_nip')
            ->where([
                'kelas_id' => $kelas->id, 
                'tanggal' => $tanggal, 
                'nip' => $nip
            ])
            ->first();
        
        $data = [];
        $success = false;
        
        if($absensi){
            $success = true;
            $data = [
                "id" => $absensi->id,
                "siswa_nip" => $absensi->siswa_nip,
                "siswa_nama" => $absensi->siswa->nama,

resources/views/temp/absensi/create.blade.php
@extends('layouts.main')

@push('title', 'Tambah Absensi Kelas')
@push('header-title', 'Tambah Absensi Kelas')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-body">
            <form action="{{ route('absensi.store', $kelas) }}" method="POST" class="form">
                @csrf
                <div class="form-group" id="row_container">
                </div>
                <div class="form-group">
                    <a href="#" class="btn btn-primary mb-1 mr-1" onclick="addRow(event)">Tambah Kolom</a>
                    <button class="btn btn-success mb-1 mr-1" id="btn-submit">Submit</button>
                    <a href="{{ route('absensi.show-kelas',$kelas) }}" class="btn btn-danger mb-1 mr-1">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    let i = 0;
    let target = document.querySelector('#row_container');
    let listRow = [];
    let getSchema = () => {
        listRow.push(`#row${i}`);

        let schema = `
            <div class="row mb-3" id="row${i}">
                <div class="col-sm-3 d-sm-flex d-block">
                    <strong class="mr-1">#${i+1}</strong>
                    <select name="siswa_nip[]" class="form-control mb-2" id="siswa_nip${i}">
                        <option value="">-- Pilih Siswa --</option>
                        @foreach($siswa as $nip => $nama)
                        <option value="{{ $nip }}">{{ $nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-3">
                    <select name="status[]" class="form-control mb-2" id="status${i}">
                        <option value="">-- Pilih Status --</option>
                        @foreach($status as $val)
                        <option value="{{ $val }}">{{ strtoupper($val) }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-4">
                        <textarea name="keterangan[]" class="form-control mb-2" id="keterangan${i}" placeholder="Keterangan"></textarea>
                </div>
                <div class="col-sm-2">
                    <a href="#" class="btn btn-danger mb-2" onclick="deleteRow(event,'#row${i}')">Delete</a>
                </div>
            </div>`;

        schema = new DOMParser().parseFromString(schema,'text/html').body;

        schema = schema.querySelector('div');

        i++;
        
        return schema;
    }
    let addRow = (e) => {
        if(e !== undefined) e.preventDefault();
        let schema = getSchema();
        target.appendChild(schema);
    }
    let deleteRow = (e,id) => {
        e.preventDefault();
        let deletedRow = document.querySelector(id);

        listRow.splice(listRow.indexOf(id),1);

        deletedRow.remove();

    }

    $('#btn-submit').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parents('form');
        Swal.fire({
            title: "Apakah anda yakin?",
            text: "Data akan ditambahkan ke dalam database setelah proses ini dijalankan.",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Ya!",
            cancelButtonText: 'Tidak',
        }).then((result) => {
            if (result.value) form.submit();
        });
    });
    addRow();
</script>
@endpush

resources/views/temp/absensi/index.blade.php
@extends('layouts.main')

@push('title', 'Daftar Absensi Kelas')
@push('header-title', 'Daftar Absensi Kelas')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-header">
        </div>
        <div class="card-body">
            <table class="table table-striped table-borderless w-100" id="table-absensi">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Kelas</th>
                        <th>Tahun Ajaran</th>
                        <th>Absen Hari Ini</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(function () {
        $('#table-absensi').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: '{{ route("datatables.absensi") }}',
            columns: [{
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'prefix',
                    name: 'prefix'
                },
                {
                    data: 'tahun_ajaran',
                    name: 'tahun_ajaran'
                },
                {
                    data: 'status_absen_hari_ini',
                    name: 'status_absen_hari_ini'
                },
                {
                    data: 'action',
                    name: 'action'
                },
            ],
        });
    });

</script>
@endpush

resources/views/temp/absensi/show-kelas.blade.php
@extends('layouts.main')

@push('title', 'Detail Kelas')
@push('header-title', 'Detail Kelas')
@push('_css')
<style>
    #advanced-filter{
        display: none;
    }
</style>
@endpush

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-danger">
        <div class="card-header">
            <a href="{{ route('absensi.index') }}" class="btn btn-danger mb-2 mr-1">Kembali</a>
        </div>
        <div class="card-body">
            <table class="table table-hover table-stripped">
                <tr>
                    <th>Kelas</th>
                    <td>{{ $kelas->getPrefix() }}</td>
                </tr>
                <tr>
                    <th>Jumlah Siswa</th>
                    <td>{{ count($kelas->siswa) }} Siswa</td>
                </tr>
                <tr>
                    <th>Wali Kelas</th>
                    <td>{{ $kelas->user->name }}</td>
                </tr>
            </table>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <a href="{{ route('absensi.create', $kelas) }}" class="btn btn-primary mb-1 mr-1">Tambah Absen Hari Ini</a>
            @if (Roles::has('Super Admin'))
                <a href="{{ route('absensi.edit', $kelas) }}" class="btn btn-primary mb-1 mr-1">Ubah Data</a>
            @endif
            <button class="btn btn-primary mb-1 mr-1" onclick="showAdvSearch()">Advanced Filter</button>
        </div>
        <div class="card-body">
            <form id="advanced-filter" class="form mb-2 pb-3">
                <div class="form-group">
                    <label for="tanggal">Tanggal</label>
                    <input type="date" name="tanggal" id="tanggal" class="form-control">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" onclick="searchData(event)">Cari Data</button>
                </div>
            </form>
            <table id="table-siswa" class="table table-hover table-stripped table-borderless w-100">
                <thead>
                    <th>NIP</th>
                    <th>Nama Siswa</th>
                    <th>Tanggal</th>
                    <th>Status</th>
                    <th>Keterangan</th>
                </thead>
            </table>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    let dtTable = $('#table-siswa').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: {
                    url: `{{ route('datatables.absensi.siswa', $kelas) }}`,
                    data: function(d){
                        d.tanggal= $('#tanggal').val();
                    }
                },
                columns: [{
                        data: 'nip',
                        name: 'nip'
                    },
                    {
                        data: 'nama',
                        name: 'nama'
                    },
                    {
                        data: 'tanggal',
                        name: 'tanggal'
                    },
                    {
                        data: 'status',
                        name: 'status'
                    },
                    {
                        data: 'keterangan',
                        name: 'keterangan'
                    },
                ],
                drawCallback: function (settings) {
                    $('.deleteAlerts').on('click', function (e) {
                        e.preventDefault();
                        let form = $(this).parents('form');
                        Swal.fire({
                            title: "Apakah anda yakin?",
                            text: "Data akan dihapus secara permanen dari database setelah proses ini dijalankan.",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "Ya!",
                            cancelButtonText: 'Tidak',
                        }).then((result) => {
                            if (result.value) $(form).submit();
                        });
                    });
                }
            });

    let searchData = (e) => {
        e.preventDefault();

        dtTable.draw();    
    }

    let showAdvSearch = () => {
        let target = document.querySelector('#advanced-filter');
        let checkAttr = target.hasAttribute('style');

        if(checkAttr){
            target.removeAttribute('style')
        }else{
            target.setAttribute('style','display: block');
        }
    }

</script>
@endpush