routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'confirm' => false, // Password Confirm Routes...
  'verify' => false, // Email Verification Routes...
]);


Route::group(['middleware' => 'auth'],function(){
    Route::get('/', function () {
        return view('welcome');
    });


    Route::group(['middleware' => 'Roles:Super Admin'], function () {
      // route hari efektif
      Route::group(['prefix' => 'hari-efektif', 'as' => 'hari-efektif.'],function() {
        Route::get('/', 'HariEfektifController@index')
          ->name('index');
        Route::put('/update/{data}', 'HariEfektifController@update')
          ->name('update');
      });
  
      // route jurusan
      Route::resource('jurusan', 'JurusanController')->except([
        'show'
      ]);
  
      // route user
      Route::resource('/user', 'UserController');
  
      // route user role
      Route::get('/user/{user}/addrole', 'UserController@addRole')
        ->name('user.add-role');
      Route::post('/user/{user}/storerole', 'UserController@storeRole')
        ->name('user.store-role');
      Route::delete('/user/{user}/removerole/{userRole}', 'UserController@removeRole')
        ->name('user.remove-role');
      Route::post('/user/{user}/reset-password', 'UserController@resetPassword')
        ->name('user.reset-password');
  
      //route kategori point
      Route::resource('kategori-point', 'KategoriPointController');
  
      // route point
      Route::get('/kategori-point/{kategori_point}/point', 'PointController@create')
        ->name('kategori-point.show.create');
      Route::post('/kategori-point/{kategori_point}/point', 'PointController@store')
        ->name('kategori-point.show.store');
      Route::get('/kategori-point/{kategori_point}/point/{point}/edit', 'PointController@edit')
        ->name('kategori-point.show.edit');
      Route::patch('/kategori-point/{kategori_point}/point/{point}/update', 'PointController@update')
        ->name('kategori-point.show.update');
      Route::delete('/kategori-point/{kategori_point}/point/{point}', 'PointController@destroy')
        ->name('kategori-point.show.destroy');

      //route hari tidak efektif
      Route::resource('hari-tidak-efektif', 'HariTidakEfektifController')->except([
        'show'
      ]);
        
    });




    // route kelas
    Route::resource('kelas', 'KelasController')->parameters([
      'kelas' => 'kelas'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route siswa
    Route::resource('/kelas/{kelas}/siswa', 'SiswaController')->except([
      'index'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route kasus
    Route::resource('/kasus', 'KasusController')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_siswa/{siswa}', 'KasusController@getSiswa')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_point/{point}', 'KasusController@getPoint')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::put('kasus/{kasus}/rollback', 'KasusController@rollback')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.rollback');

    //  route absensi
    Route::get('/absensi', 'AbsensiController@index')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.index');
    Route::get('/absensi/{kelas}', 'AbsensiController@showKelas')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.show-kelas');
    Route::get('/absensi/{kelas}/create', 'AbsensiController@create')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.create');
    Route::POST('/absensi/{kelas}/store', 'AbsensiController@store')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.store');
    Route::get('/absensi/{kelas}/edit', 'AbsensiController@edit')
      ->middleware('Roles:Super Admin')
      ->name('absensi.edit');
    Route::POST('/absensi/{kelas}/edit/get-data', 'AbsensiController@getDataSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.edit.get-data');
    Route::PUT('/absensi/{kelas}/update', 'AbsensiController@update')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.update');
});




/*
|--------------------------------------------------------------------------
| Web Routes Data Tables
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware'=> 'auth', 'prefix' => 'datatables', 'as' => 'datatables.'],function(){
    Route::get('hari-efektif/json', 'HariEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-efektif');

    Route::get('jurusan/json', 'JurusanController@json')
      ->middleware('Roles:Super Admin')
      ->name('jurusan');

    Route::get('kelas/json', 'KelasController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas');

    Route::get('kelas/{kelas}/siswa/json', 'SiswaController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa');

    Route::get('/kelas/{kelas}/siswa/{siswa}/pelanggaran/json', 'SiswaController@getPelanggaran')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.pelanggaran');

    Route::get('/kelas/{kelas}/siswa/{siswa}/penghargaan/json', 'SiswaController@getPenghargaan')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.penghargaan');

    Route::get('/users/json', 'UserController@json')
      ->middleware('Roles:Super Admin')
      ->name('user');

    Route::get('/hari-tidak-efektif/json', 'HariTidakEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-tidak-efektif');

    Route::get('/kategori-point/json', 'KategoriPointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point');

    Route::get('kategori-point/{kategori_point}/point/json', 'PointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point.show.point');

    Route::get('/kasus/json', 'KasusController@json')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus');

    Route::get('absensi/json', 'AbsensiController@json')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi');

    Route::get('absensi/{kelas}/json', 'AbsensiController@jsonSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.siswa');

});




/*
|--------------------------------------------------------------------------
| Web Routes Select 2
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware' => 'auth', 'prefix' => 'select2', 'as' => 'select2.'],function(){
    Route::post('/kasus/kelas/{kelas}/siswa', 'KasusController@siswa')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.siswa');

    Route::post('/kasus/{kategori_point}/point', 'KasusController@point')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.point');

    Route::post('kelas/guru/json', 'KelasController@guru')
      ->middleware('Roles:Super Admin')
      ->name('kelas.guru');

});

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    protected $table = "kelas";
    protected $fillable = [
        "kelas",
        "grade",
        "jurusan_id",
        "nama_kelas",
        "wali_kelas_id",
        "tahun_ajaran_id",
    ];

    function getTotalPoint($column,$id){
        $pointKelas = $this->join('siswa','kelas_id','kelas.id')
            ->groupBy('kelas_id')
            ->having('kelas_id',$id)
            ->sum( $column );
        return $pointKelas. " Point";
    }

    function siswa() {
        return $this->hasMany(Siswa::class);
    }
    function jurusan() {
        return $this->belongsTo(Jurusan::class);
    }
    function petugas() {
        return $this->belongsTo(User::class,'petugas_id');
    }
}

app/Http/Controllers/KelasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Jurusan;
use App\Models\User;
use App\Models\UserRoles;
use App\Models\Role;
use App\Models\Siswa;
use App\Models\Kasus;
use Illuminate\Http\Request;
use App\Http\Requests\KelasRequest;
use DB;
use Roles;

class KelasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('kelas.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tahun = [];
        
        $startYear = date('Y');
        $endYear = date('Y') + 6;

        while($startYear < $endYear){
            $schema = $startYear. "/". ($startYear+1);
            array_push($tahun,$schema);
            $startYear += 1;
        }

        $jurusan = Jurusan::select(['id','nama'])->get();

        return view('kelas.create',compact('jurusan','tahun'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KelasRequest $request)
    {
        $schema = [
            "user_id" => $request->walikelas,
            "jurusan_id" => $request->jurusan_id,
            "grade" => strtoupper($request->grade),
            "kelas_x" => ($request->kelas == "x" ? true : false),
            "kelas_xi" => ($request->kelas == "xi" ? true : false),
            "kelas_xii" => ($request->kelas == "xii" ? true : false),
            "tahun_ajaran" => $request->tahun_ajaran,
        ];
        
        $kelas = new Kelas($schema);

        if($kelas->save()){
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('success', 'Kelas berhasil dibuat.');
        }else{
            return redirect()
                ->route('kelas.create')
                ->with('error', 'Kelas gagal dibuat.');
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function show(Kelas $kelas)
    {
        $kasus = Kasus::join('siswa', 'siswa.nip', 'siswa_nip')
            ->where( ['kelas_id' => $kelas->id] )
            ->orderBy('kasus.created_at','ASC')
            ->limit(3)
            ->get();

        if( Roles::checkAuthorization($kelas) == false ){
            return abort(403);
        }

        return view('kelas.show', compact('kelas','kasus'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function edit(Kelas $kelas)
    {
        return view('kelas.edit', compact('kelas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function update(KelasRequest $request, Kelas $kelas)
    {
        $schema = [
            "user_id" => $request->walikelas
        ];

        if($kelas->update($schema)){
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('success', 'Kelas berhasil diubah.');
        }else{
            return redirect()
                ->route('kelas.show', $kelas)
                ->with('error', 'Kelas gagal diubah.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Kelas  $kelas
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kelas $kelas)
    {
        DB::beginTransaction();

        try{
            $kelas->delete();

            DB::commit();

            return redirect()
                ->route('kelas.index')
                ->with('success', 'Kelas berhasil dihapus.');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()
                ->route('kelas.index')
                ->with('error', 'Kelas gagal dihapus. Masih ada data siswa yang ter-relasi dengan data ini.');
        }
    }

    public function json(){

        if(\Roles::has('Super Admin')){
            $data = Kelas::orderBy('created_at','DESC')->get();
        }else{
            $user_id = auth()->user()->id;
            $data = Kelas::where( ['user_id' => $user_id] )
                ->orderBy('created_at','DESC')
                ->get();
        }

        return datatables()
                ->of($data)
                ->addColumn('kelas',function($data){
                    return $data->getKelas();
                })
                ->addColumn('prefix',function($data){
                    return $data->getPrefix();
                })
                ->editColumn('jurusan',function($data){
                    return $data->jurusan->nama;
                })
                ->addColumn('akumulasi_point_pelanggaran',function($data) {
                    return $data->getTotalPoint( 'point_pelanggaran',$data->id );
                })
                ->addColumn('akumulasi_point_penghargaan',function($data) {
                    return $data->getTotalPoint( 'point_penghargaan',$data->id );
                })
                ->removeColumn([
                    'kelas_x',
                    'kelas_xi',
                    'kelas_xii',
                    'updated_at',
                    'created_at'
                ])
                ->addColumn('action',function($data){
                    $routeEdit = route('kelas.edit', $data);
                    $routeDetail = route('kelas.show', $data);
                    $routeDestroy = route('kelas.destroy', $data);

                    $token = csrf_token();
                    $method = "<input type='hidden' name='_method' value='delete'>";
                    $csrf = "<input type='hidden' name='_token' value='$token'>";

                    $buttonEdit = "
                            <a href='$routeEdit' class='btn btn-primary mb-1 mr-1'>
                                <i class='fa fa-pencil-alt'></i> Ubah
                            </a>";
                    
                    $buttonDetail = "
                            <a href='$routeDetail' class='btn btn-warning mb-1 mr-1'>
                                <span class='fas fa-eye'></span> Detail
                            </a>";

                    $buttonDestroy = "
                            <form action='$routeDestroy' class='d-inline-block' method='post'>
                                $csrf
                                $method
                                <button class='btn btn-danger mb-1 mr-1 deleteAlerts'>
                                    <span class='fa fa-trash-alt'></span> Hapus
                                </button>
                            </form>";


                    if(\Roles::has('Super Admin')){
                        $button = "$buttonEdit $buttonDetail $buttonDestroy";
                    }else{
                        $button = "$buttonDetail";
                    }

                    return $button;
                })
                ->make(true);
    }

    public function guru(Request $request){
        $search = $request->search;

        $guru = User::whereIn('id',function($q) {
            $q->select('user_roles.user_id')
                ->from('user_roles')
                ->whereColumn('user_roles.user_id','users.id')
                ->join('roles','user_roles.role_id','=','roles.id')
                ->whereNotIn('user_id',function($q2){
                    $q2->select('user_roles.user_id')
                        ->from('user_roles')
                        ->join('kelas', 'kelas.user_id', 'user_roles.user_id');
                })
                ->where(['roles.nama' => 'Wali Kelas']);
        });

        if($search != ''){
            $guru = $guru->where('name','like',"%$search%")->limit(6)->get();
        }else{
            $guru = $guru->limit(6)->get();
        }

        $response = [];
        $selected = (int)$request->selected;

        foreach($guru as $row){
            if($selected == $row->id):
                array_push($response,[
                    'id' => $row->id,
                    'text' => $row->name,
                    'selected' => true,
                ]);
            else:
                array_push($response,[
                    'id' => $row->id,
                    'text' => $row->name
                ]);
            endif;
        }

        return response()->json($response);
    }

}

resources/views/temp/kelas/create.blade.php
@extends('layouts.main')

@push('title', 'Tambah Kelas')
@push('header-title', 'Tambah Kelas')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-body">
            <form action="{{ route('kelas.store') }}" method="POST" class="form">
                @csrf
                <div class="form-group">
                    <label for="tahun_ajaran">Tahun Ajaran</label>
                    <select name="tahun_ajaran" id="tahun_ajaran" class="form-control">
                        <option value="">-- Pilih Ajaran --</option>
                        @foreach ($tahun as $item)
                        <option value="{{ $item }}">{{ $item }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="jurusan">Jurusan</label>
                    <select name="jurusan_id" id="jurusan" class="form-control">
                        <option value="">-- Pilih Ajaran --</option>
                        @foreach ($jurusan as $item)
                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label for="kelas">Kelas</label>
                    <select name="kelas" id="kelas" class="form-control">
                        <option value="">-- Pilih Kelas --</option>
                        <option value="x">Kelas X</option>
                        <option value="xi">Kelas XI</option>
                        <option value="xii">Kelas XII</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="grade">Grade</label>
                    <select name="grade" id="grade" class="form-control">
                        <option value="">-- Pilih Grade --</option>
                        <option value="a">A</option>
                        <option value="b">B</option>
                        <option value="c">C</option>
                        <option value="d">D</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="guru">Wali Kelas</label>
                    <select name="walikelas" id="guru" class="form-control select2bs4">
                        <option value="">-- Pilih Wali Kelas --</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-submit">
                        Submit
                    </button>
                    <a href="{{ route('kelas.index') }}" class="btn btn-danger">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $(document).ready(function () {
        $("#guru").select2({
            ajax: {
                url: "{{route('select2.kelas.guru')}}",
                type: "post",
                dataType: 'json',
                delay: 10,
                data: function (params) {
                    return {
                        _token: CSRF_TOKEN,
                        search: params.term // search term
                    };
                },
                processResults: function (response) {
                    return {
                        results: response
                    };
                },
                cache: true
            }
        });

        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            Swal.fire({
                title: "Apakah anda yakin?",
                text: "Data akan ditambahkan ke dalam database setelah proses ini dijalankan.",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya!",
                cancelButtonText: 'Tidak',
            }).then((result) => {
                if (result.value) form.submit();
            });
        });
    });

</script>
@endpush

resources/views/temp/kelas/edit.blade.php
@extends('layouts.main')

@push('title', 'Ubah Kelas')
@push('header-title', 'Ubah Kelas')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-body">
            <form action="{{ route('kelas.update', $kelas) }}" method="POST" class="form">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="tahun_ajaran">Tahun Ajaran</label>
                    <select name="tahun_ajaran" id="tahun_ajaran" class="form-control" disabled>
                        <option value="">{{ $kelas->tahun_ajaran }}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="jurusan">Jurusan</label>
                    <select name="jurusan_id" id="jurusan" class="form-control" disabled>
                        <option value="">{{ $kelas->jurusan->nama }}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="kelas">Kelas</label>
                    <select name="kelas" id="kelas" class="form-control" disabled>
                        <option value="">{{ $kelas->getKelas() }}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="grade">Grade</label>
                    <select name="grade" id="grade" class="form-control" disabled>
                        <option value="">{{ $kelas->grade }}</option>
                    </select>
                </div>
                <div class="form-group w-100">
                    <label for="guru">Wali Kelas</label>
                    <span class="d-block mb-1">Guru saat ini : <strong>{{ $kelas->user->name }}</strong></span>
                    <select name="walikelas" id="guru" class="form-control select2bs4">
                        <option value="">-- Pilih Wali Kelas --</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success" id="btn-submit">
                        Submit
                    </button>
                    <a href="{{ route('kelas.index') }}" class="btn btn-danger">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $(document).ready(function () {
        $("#guru").select2({
            ajax: {
                url: "{{route('select2.kelas.guru')}}",
                type: "post",
                dataType: 'json',
                delay: 10,
                data: function (params) {
                    return {
                        _token: CSRF_TOKEN,
                        selected: "{{ $kelas->user_id }}",
                        search: params.term // search term
                    };
                },
                processResults: function (response) {
                    return {
                        results: response
                    };
                },
                cache: true
            }
        })

        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            Swal.fire({
                title: "Apakah anda yakin?",
                text: "Data akan ditambahkan ke dalam database setelah proses ini dijalankan.",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Ya!",
                cancelButtonText: 'Tidak',
            }).then((result) => {
                if (result.value) form.submit();
            });
        });
    });

</script>
@endpush

resources/views/temp/kelas/index.blade.php
@extends('layouts.main')

@push('title', 'Daftar Kelas')
@push('header-title', 'Daftar Kelas')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-header">
            @if (Roles::has('Super Admin'))
                <a href="{{ route('kelas.create') }}" class="btn btn-success mr-1 mb-1">Tambah</a>
            @endif
        </div>
        <div class="card-body">
            <table class="table table-striped table-borderless w-100" id="kelas-table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Prefix</th>
                        <th>Tahun Ajaran</th>
                        <th>Penghargaan</th>
                        <th>Pelanggaran</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(function () {
        $('#kelas-table').DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: '{{ route("datatables.kelas") }}',
            columns: [{
                    data: 'id',
                    name: 'id'
                },
                {
                    data: 'prefix',
                    name: 'prefix'
                },
                {
                    data: 'tahun_ajaran',
                    name: 'tahun_ajaran'
                },
                {
                    data: 'akumulasi_point_penghargaan',
                    name: 'akumulasi_point_penghargaan'
                },
                {
                    data: 'akumulasi_point_pelanggaran',
                    name: 'akumulasi_point_pelanggaran'
                },
                {
                    data: 'action',
                    name: 'action'
                },
            ],
            drawCallback: function (settings) {
                $('.deleteAlerts').on('click', function (e) {
                    e.preventDefault();
                    let form = $(this).parents('form');
                    Swal.fire({
                        title: "Apakah anda yakin?",
                        text: "Data akan dihapus secara permanen dari database setelah proses ini dijalankan.",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Ya!",
                        cancelButtonText: 'Tidak',
                    }).then((result) => {
                        if (result.value) $(form).submit();
                    })
                });
            }
        });
    });

</script>
@endpush