routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the 'web' middleware group. Now create something great!
|
*/

Auth::routes([
  'register' => false, // Registration Routes...
  'reset' => false, // Password Reset Routes...
  'confirm' => false, // Password Confirm Routes...
  'verify' => false, // Email Verification Routes...
]);


Route::group(['middleware' => 'auth'],function(){
    Route::get('/', function () {
        return view('welcome');
    });


    Route::group(['middleware' => 'Roles:Super Admin'], function () {
      // route hari efektif
      Route::group(['prefix' => 'hari-efektif', 'as' => 'hari-efektif.'],function() {
        Route::get('/', 'HariEfektifController@index')
          ->name('index');
        Route::put('/update/{data}', 'HariEfektifController@update')
          ->name('update');
      });
  
      // route jurusan
      Route::resource('jurusan', 'JurusanController')->except([
        'show'
      ]);
  
      // route user
      Route::resource('/user', 'UserController');
  
      // route user role
      Route::get('/user/{user}/addrole', 'UserController@addRole')
        ->name('user.add-role');
      Route::post('/user/{user}/storerole', 'UserController@storeRole')
        ->name('user.store-role');
      Route::delete('/user/{user}/removerole/{userRole}', 'UserController@removeRole')
        ->name('user.remove-role');
      Route::post('/user/{user}/reset-password', 'UserController@resetPassword')
        ->name('user.reset-password');
  
      //route kategori point
      Route::resource('kategori-point', 'KategoriPointController');
  
      // route point
      Route::get('/kategori-point/{kategori_point}/point', 'PointController@create')
        ->name('kategori-point.show.create');
      Route::post('/kategori-point/{kategori_point}/point', 'PointController@store')
        ->name('kategori-point.show.store');
      Route::get('/kategori-point/{kategori_point}/point/{point}/edit', 'PointController@edit')
        ->name('kategori-point.show.edit');
      Route::patch('/kategori-point/{kategori_point}/point/{point}/update', 'PointController@update')
        ->name('kategori-point.show.update');
      Route::delete('/kategori-point/{kategori_point}/point/{point}', 'PointController@destroy')
        ->name('kategori-point.show.destroy');

      //route hari tidak efektif
      Route::resource('hari-tidak-efektif', 'HariTidakEfektifController')->except([
        'show'
      ]);
        
    });




    // route kelas
    Route::resource('kelas', 'KelasController')->parameters([
      'kelas' => 'kelas'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route siswa
    Route::resource('/kelas/{kelas}/siswa', 'SiswaController')->except([
      'index'
    ])->middleware('Roles:Super Admin|Wali Kelas');

    // route kasus
    Route::resource('/kasus', 'KasusController')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_siswa/{siswa}', 'KasusController@getSiswa')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::post('kasus/get_point/{point}', 'KasusController@getPoint')
      ->middleware('Roles:Super Admin|Petugas Konseling');
    Route::put('kasus/{kasus}/rollback', 'KasusController@rollback')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.rollback');

    //  route absensi
    Route::get('/absensi', 'AbsensiController@index')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.index');
    Route::get('/absensi/{kelas}', 'AbsensiController@showKelas')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.show-kelas');
    Route::get('/absensi/{kelas}/create', 'AbsensiController@create')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.create');
    Route::POST('/absensi/{kelas}/store', 'AbsensiController@store')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.store');
    Route::get('/absensi/{kelas}/edit', 'AbsensiController@edit')
      ->middleware('Roles:Super Admin')
      ->name('absensi.edit');
    Route::POST('/absensi/{kelas}/edit/get-data', 'AbsensiController@getDataSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.edit.get-data');
    Route::PUT('/absensi/{kelas}/update', 'AbsensiController@update')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.update');
});




/*
|--------------------------------------------------------------------------
| Web Routes Data Tables
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware'=> 'auth', 'prefix' => 'datatables', 'as' => 'datatables.'],function(){
    Route::get('hari-efektif/json', 'HariEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-efektif');

    Route::get('jurusan/json', 'JurusanController@json')
      ->middleware('Roles:Super Admin')
      ->name('jurusan');

    Route::get('kelas/json', 'KelasController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas');

    Route::get('kelas/{kelas}/siswa/json', 'SiswaController@json')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa');

    Route::get('/kelas/{kelas}/siswa/{siswa}/pelanggaran/json', 'SiswaController@getPelanggaran')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.pelanggaran');

    Route::get('/kelas/{kelas}/siswa/{siswa}/penghargaan/json', 'SiswaController@getPenghargaan')
      ->middleware('Roles:Super Admin|Wali Kelas')
      ->name('kelas.show.siswa.penghargaan');

    Route::get('/users/json', 'UserController@json')
      ->middleware('Roles:Super Admin')
      ->name('user');

    Route::get('/hari-tidak-efektif/json', 'HariTidakEfektifController@json')
      ->middleware('Roles:Super Admin')
      ->name('hari-tidak-efektif');

    Route::get('/kategori-point/json', 'KategoriPointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point');

    Route::get('kategori-point/{kategori_point}/point/json', 'PointController@json')
      ->middleware('Roles:Super Admin')
      ->name('kategori-point.show.point');

    Route::get('/kasus/json', 'KasusController@json')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus');

    Route::get('absensi/json', 'AbsensiController@json')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi');

    Route::get('absensi/{kelas}/json', 'AbsensiController@jsonSiswa')
      ->middleware('Roles:Super Admin|Petugas Absensi')
      ->name('absensi.siswa');

});




/*
|--------------------------------------------------------------------------
| Web Routes Select 2
|--------------------------------------------------------------------------
|
*/

Route::group(['middleware' => 'auth', 'prefix' => 'select2', 'as' => 'select2.'],function(){
    Route::post('/kasus/kelas/{kelas}/siswa', 'KasusController@siswa')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.siswa');

    Route::post('/kasus/{kategori_point}/point', 'KasusController@point')
      ->middleware('Roles:Super Admin|Petugas Konseling')
      ->name('kasus.point');

    Route::post('kelas/guru/json', 'KelasController@guru')
      ->middleware('Roles:Super Admin')
      ->name('kelas.guru');

});

app/Http/Controllers/KategoriPointController.php
<?php

namespace App\Http\Controllers;

use App\Models\KategoriPoint;
use App\Http\Requests\KategoriPointRequest;
use Illuminate\Http\Request;
use DB;


class KategoriPointController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('kategori-point.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $jenisPoint = [
            'positif',
            'negatif'
        ];
        
        return view('kategori-point.create',compact('jenisPoint'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(KategoriPointRequest $request)
    {
        $kategoriPoint = new KategoriPoint( $request->all() );

        if($kategoriPoint->save())
            return redirect()
                ->route('kategori-point.index')
                ->with('success', 'Kategori point berhasil ditambahkan');
        else
            return redirect()
                ->route('kategori-point.index')
                ->with('error', 'Kategori point gagal ditambahkan');
    }

    /**
     * Display specific resource
     * 
     * @param \App\Models\KategoriPoint $kategoriPoint
     * @return \Illuminate\Http\Response
     */
    public function show(KategoriPoint $kategoriPoint){
        return view('kategori-point.show', compact('kategoriPoint'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\KategoriPoint  $kategoriPoint
     * @return \Illuminate\Http\Response
     */
    public function edit(KategoriPoint $kategoriPoint)
    {
        $jenisPoint = [
            'positif',
            'negatif'
        ];

        return view('kategori-point.edit', compact('kategoriPoint','jenisPoint'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\KategoriPoint  $kategoriPoint
     * @return \Illuminate\Http\Response
     */
    public function update(KategoriPointRequest $request, KategoriPoint $kategoriPoint)
    {
        if($kategoriPoint->update( $request->all() ))
            return redirect()
                ->route('kategori-point.index')
                ->with('success', 'Kategori point berhasil diubah');
        else
            return redirect()
                ->route('kategori-point.index')
                ->with('success', 'Kategori point gagal diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\KategoriPoint  $kategoriPoint
     * @return \Illuminate\Http\Response
     */
    public function destroy(KategoriPoint $kategoriPoint)
    {
        DB::beginTransaction();
        try{
            $kategoriPoint->delete();
            DB::commit();
            return redirect()
                ->route('kategori-point.index')
                ->with('success', 'Kategori point berhasil dihapus');
        }catch(\Exception $e){
            DB::rollback();
            return redirect()
                ->route('kategori-point.index')
                ->with('error', 'Kategori point gagal dihapus. Masih ada data point yang ter-relasi dengan data ini.');
        }
    }

    /**
     * Display JSON Datatable Data
     * 
     */
    public function json(){
        $kategoriPoint = KategoriPoint::orderBy('created_at','DESC')
            ->select(['id','nama','jenis_point'])
            ->get();

        $datatables = datatables()
            ->of($kategoriPoint)
            ->addColumn('action',function($data){
                $routeUpdate = route('kategori-point.edit',$data);
                $routeDetail = route('kategori-point.show',$data);
                $routeDestroy = route('kategori-point.destroy',$data);

                $token = csrf_token();
                $csrf = "<input type='hidden' value='$token' name='_token'>";
                $method = "<input type='hidden' value='DELETE' name='_method'>";
                
                $buttonUpdate = "
                            <a href='$routeUpdate' class='btn btn-primary mb-1 mr-1'>
                                    <i class='fa fa-pencil-alt'></i> Ubah</a>";
                $buttonDetail = "
                            <a href='$routeDetail' class='btn btn-warning mb-1 mr-1'>
                                    <i class='fa fa-eye'></i> Detail</a>";
                $buttonDestroy = "
                            <form action='$routeDestroy' method='post' class='d-inline-block'> 
                                $csrf 
                                $method 
                                <button class='btn btn-danger mb-1 mr-1 deleteAlerts'>
                                    <i class='fa fa-trash'></i> 
                                    Hapus
                                </button>
                            </form>";
                
                $html = "$buttonUpdate $buttonDetail $buttonDestroy";

                return $html;
            })
            ->editColumn('jenis_point',function($data){
                return $data->getJenisPoint();
            })
            ->make(true);

        return $datatables;
    }
}

resources/views/temp/kategori-point/create.blade.php
@extends('layouts.main')

@push('title','Tambah Kategori Point')
@push('header-title','Tambah Kategori Point')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-default">
        <div class="card-header">
            <form method="post" action="{{ route('kategori-point.store') }}">
                @csrf
                <div class="form-group">
                    <label for="nama"">Nama</label>
                    <input type=" text" class="form-control" id="nama" placeholder="Masukkan nama" name="nama">
                </div>
                <div class="form-group">
                    <label for="jenis_point"">Jenis Point</label>
                    <select name=" jenis_point" class="form-control" id="jenis_point" name="jenis_point">
                        <option value="">-- Pilih Jenis Point --</option>
                        @foreach ($jenisPoint as $val)
                        <option value="{{ $val }}">{{ strtoupper($val) }}</option>
                        @endforeach
                        </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success mb-1 mr-1" id="btn-submit">Submit</button>
                    <a href="{{ route('kategori-point.index') }}" class="btn btn-danger mb-1 mr-1">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('_js')
<script>
    $('#btn-submit').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parents('form');
        Swal.fire({
            title: "Apakah anda yakin?",
            text: "Data akan ditambahkan kedalam database setelah proses ini dijalankan.",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Ya!",
            cancelButtonText: 'Tidak',
        }).then((result) => {
            if (result.value) form.submit();
        });
    });

</script>
@endpush

resources/views/temp/kategori-point/edit.blade.php
@extends('layouts.main')

@push('title', 'Ubah Kategori Point')
@push('header-title', 'Ubah Kategori Point')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-default">
        <div class="card-header">
            <form method="post" action="{{ route('kategori-point.update', $kategoriPoint->id) }}">
                @method('patch')
                @csrf
                <div class="form-group">
                    <label for="nama"">Nama</label>
                    <input type=" text" class="form-control" id="nama" placeholder="Masukkan nama" name="nama"
                        value="{{ $kategoriPoint->nama }}">
                </div>
                <div class="form-group">
                    <label for="jenis_point"">Jenis Point</label>
                    <select name=" jenis_point" class="form-control" id="jenis_point" name="jenis_point">
                        <option value="">-- Pilih Jenis Point --</option>
                        @foreach ($jenisPoint as $val)
                        <option value="{{ $val }}" @if($val==$kategoriPoint->jenis_point) selected @endif
                            >{{ strtoupper($val) }}</option>
                        @endforeach
                        </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-success mb-1 mr-1" id="btn-submit">Submit</button>
                    <a href="{{ route('kategori-point.index') }}" class="btn btn-danger mb-1 mr-1">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

@push('_js')
<script>
    $('#btn-submit').on('click', function (e) {
        e.preventDefault();
        var form = $(this).parents('form');
        Swal.fire({
            title: "Apakah anda yakin?",
            text: "Data akan diubah setelah proses ini dijalankan.",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Ya!",
            cancelButtonText: 'Tidak',
        }).then((result) => {
            if (result.value) form.submit();
        });
    });

</script>
@endpush

resources/views/temp/kategori-point/index.blade.php
@extends('layouts.main')

@push('title','Kategori Point')
@push('header-title','Daftar Kategori Point')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-success">
        <div class="card-header">
            <a href="{{ route('kategori-point.create') }}" class="btn btn-success">Tambah</a>
        </div>
        <div class="card-body">
            <table class="table table-hover table-borderless" id="kategori-point-table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nama</th>
                        <th scope="col">Jenis Point</th>
                        <th scope="col">aksi</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@endsection

@push('_js')
<script>
$(function() {
    $('#kategori-point-table').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        ajax: '{{ route("datatables.kategori-point") }}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'nama', name: 'nama' },
            { data: 'jenis_point', name: 'jenis_point' },
            { data: 'action', name: 'action' },
        ],
        drawCallback: function(settings){
            $('.deleteAlerts').on('click', function(e) {
                e.preventDefault();
                let form = $(this).parents('form');
                Swal.fire({
                    title: "Apakah anda yakin?",
                    text: "Data akan dihapus secara permanen dari database setelah proses ini dijalankan.",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Ya!",
                    cancelButtonText: 'Tidak',
                }).then( (result) =>{
                    if(result.value) $(form).submit();
                })
            });
        }
    });
});

</script>
@endpush

resources/views/temp/kategori-point/show.blade.php
@extends('layouts.main')

@push('title','Detail Kategori Point')
@push('header-title','Detail Kategori Point')

@section('content')
<div class="col-md-12">
    <x-alerts :data="$errors" />
    <div class="card card-danger">
        <div class="card-header">
            <a href="{{ route('kategori-point.index') }}" class="btn btn-danger mb-2 mr-1">Kembali</a>
        </div>
        <div class="card-body">
            <table class="table table-hover table-stripped">
                <tr>
                    <th>Nama</th>
                    <td>{{ $kategoriPoint->nama }}</td>
                </tr>
                <tr>
                    <th>Jenis Point</th>
                    <td>{{ $kategoriPoint->getJenisPoint() }}</td>
                </tr>
                <tr>
                    <th>Jumlah Point</th>
                    <td>{{ count($kategoriPoint->point) }} Data</td>
                </tr>
            </table>
        </div>
    </div>
</div>

<div class="col-md-12">
    <div class="card card-success">
        <div class="card-header">
            <a href="{{ route('kategori-point.show.create',$kategoriPoint) }}" class="btn btn-success mb-1 mr-1">Tambah
                Point</a>
        </div>
        <div class="card-body">
            <table id="table-point" class="table table-hover table-stripped table-borderless w-100">
                <thead>
                    <th scope="col">#</th>
                    <th scope="col">Peraturan</th>
                    <th scope="col">Point</th>
                    <th scope="col">Interval waktu (Berturut-turut)</th>
                    <th scope="col">Sanksi</th>
                    <th scope="col">Action</th>
                </thead>
            </table>
        </div>
    </div>
</div>
@stop

@push('_js')
<script>
    $(function () {
        $(document).ready(function () {
            $('#table-point').DataTable({
                processing: true,
                serverSide: true,
                responsive: true,
                ajax: "{{ route('datatables.kategori-point.show.point',$kategoriPoint) }}",
                columns: [{
                        data: 'id',
                        name: 'id'
                    },
                    {
                        data: 'peraturan',
                        name: 'peraturan'
                    },
                    {
                        data: 'point',
                        name: 'point'
                    },
                    {
                        data: 'interval_waktu',
                        name: 'interval_waktu'
                    },
                    {
                        data: 'sanksi',
                        name: 'sanksi'
                    },
                    {
                        data: 'action',
                        name: 'action'
                    },
                ],
                drawCallback: function (settings) {
                    $('.deleteAlerts').on('click', function (e) {
                        e.preventDefault();
                        let form = $(this).parents('form');
                        Swal.fire({
                            title: "Apakah anda yakin?",
                            text: "Data akan dihapus secara permanen dari database setelah proses ini dijalankan.",
                            showCancelButton: true,
                            confirmButtonColor: "#DD6B55",
                            confirmButtonText: "Ya!",
                            cancelButtonText: 'Tidak',
                        }).then((result) => {
                            if (result.value) $(form).submit();
                        });
                    });
                }
            });
        });
    });

</script>
@endpush